name: Build and Test

on:
  push:
    paths: 
      - 'src/exercise.py'

jobs:
      
  test_and_comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3.1.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt   
    - name: Test student program
      run: python3 -m pytest >> .github/ISSUE_TEMPLATE/test-failure.md
    - name: Failure message
      if: failure()
      uses: machine-learning-apps/pr-comment@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .github/ISSUE_TEMPLATE/test-failure.md    
    - name: Lint student program
      run: flake8 src/exercise.py
    - name: Success message
      uses: machine-learning-apps/pr-comment@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .github/ISSUE_TEMPLATE/test-success.md
